export { default as MainPage } from './MainPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as ProductsPage } from './ProductsPage'
export { default as ProductPage } from './ProductPage'
export { default as FavoritesPage } from './FavoritesPage'